os: linux
dist: xenial
language: node_js
node_js:
- node
cache: npm
notifications:
  slack:
    rooms:
      secure: GUIulM6oh7bIUmX2Gr59tlycSjd4uDz4mFtaRyjVzXqHqYgZU9WsscaFimtKjVUc85Kx8m/29jm8jMeMFA34I8814KRabXC+xI6FxMx0JnPqJ19VPPspJD+y5L28X1qPbNrMMxneEXPf3/+FourZWqUX1MgT6pFs/Wp8T1VJXXnJpNBQ5nG1ehxNvguVDl3sTpJjvVmxCJ33pzqXfLSDrdmgV3IVkJwj/NkZp/Zw5ocsD8Yc1kgt0oFHmncVYIk6s4SPIVwCCVGRvZpTCCRJAWR6tVNaPQ+ff1K7plDIO970zAEPJy8D3kxi8tiG/uEfbvbh793lyc08RwOvbk4AoWeBQwB2jztud63TonCXVT1UeL+Kna65qrNT99jVCzURv2Hef8j9e7X4X4c3oL9TXz1u6Wn7R6mFPv2hITLKUXwJ+HEXgpTCiNRiSgwQARJWcNl69tgoqtop3PWX5uIl+yGPvCtYxlYxALfNsmxFGlVrBglWuxkNmBfuK2b4VuxFxfEHzYQyX/R58Fegnl8a9z71sGI+oyysxwfZc5NgCt9gY+ICrLAdoZU/oTFixIi30tGe7c5RhnsVM92YUUeZW7BZtjIYW14aSpa2QXDeaQwhx5TV8LDAR2mIz1KWGjW6R3onggj4RMQZbfdctyhZWvBxCO31cPEggNIipGvRmyM=
before_install:
- openssl aes-256-cbc -K $encrypted_f217180e22ee_key -iv $encrypted_f217180e22ee_iv
  -in .travis/id_rsa.enc -out ./deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 ./deploy_key
- ssh-add ./deploy_key
- ssh -i ./deploy_key root@$IP pwd
install:
- cd frontend
- npm i
- cd ../backend
- npm i
script:
- npm run lint
- rm -r node_modules
- cd ../frontend
- npm run lint
- npm run build
- cd ..
addons:
  ssh_known_hosts: 165.227.158.125
deploy:
- provider: script
  skip_cleanup: true
  script: chmod +x .travis/deploy.sh && .travis/deploy.sh
  on:
    branch: production
