language: node_js
node_js:
- node
cache: npm
before_install:
- openssl aes-256-cbc -K $encrypted_f217180e22ee_key -iv $encrypted_f217180e22ee_iv
  -in .travis/id_rsa.enc -out ./deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 ./deploy_key
- ssh-add ./deploy_key
- ssh -i ./deploy_key root@165.227.158.125 pwd
install:
- cd backend
- npm i
- cd ..
- cd frontend
- npm i
- cd ..
script:
- cd frontend
- npm run lint
- npm run build
- ls
- cd ..

addons:
  ssh_known_hosts: 165.227.158.125

before_deploy:
  - chmod +x .travis/deploy.sh

deploy:
- provider: script
  skip_cleanup: true
  # script: chmod +x .travis/deploy.sh && .travis/deploy.sh
  script: ".travis/deploy.sh"
  on:
    branch: dev